# Generated by Django 5.0.4 on 2024-04-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='precio',
        ),
    ]
