# Generated by Django 5.0.4 on 2024-04-06 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(choices=[(1, 'En espera'), (2, 'En preparación'), (3, 'Listo para recoger')], default=1)),
                ('tipo', models.IntegerField(choices=[(1, 'Para llevar'), (2, 'Consumo en el sitio')])),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productApp.product')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.order')),
            ],
        ),
    ]
