# Generated by Django 5.0.4 on 2024-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_order_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'En espera'), (2, 'En preparación'), (3, 'Listo para recoger')], default=1, null=True),
        ),
    ]
